SELECT DISTINCT
	"AGE"
FROM
	"STUDENT",
	"ENROLLED",
	"COURSE",
	"FACULTY"
WHERE
	(
		"STUDENT"."SNUM" = "ENROLLED"."SNUM"
		AND "ENROLLED"."CNUM" = "COURSE"."CNUM"
		AND "COURSE"."FID" = "FACULTY"."FID"
		AND "FACULTY".FNAME = 'Zobair'
	)
OR ("STUDENT"."MAJOR" = 'ME')
AND "STUDENT"."SLEVEL" = '3'